Repository hashicorp/hc-install, pull requests merged in 2021-11, with the labels that each got.

#29 fix: avoid crash in installer
  installer.go
Labels: bug

#36 Enable log instrumentation via SetLogger
  installer.go
  installer_test.go
Labels: enhancement

#37 Sort versions from releases JSON response
  .go-version
  fs/fs_unix.go
  fs/fs_unix_test.go
  go.mod
  internal/releasesjson/checksum_downloader.go
  internal/releasesjson/product_version.go
  internal/releasesjson/releases.go
  releases/latest_version.go
  releases/versions.go
  releases/versions_test.go
Labels: enhancement

#40 fs.AnyVersion: Introduce ExactBinPath
  fs/any_version.go
  fs/fs_unix_test.go
  fs/fs_windows_test.go
Labels: enhancement

#42 fs: Fixes and unit testing for (AnyVersion).Validate()
  fs/any_version.go
  fs/any_version_test.go
Labels: bug

#45 fs: Replace os.Setenv() usage in testing with (testing.T).Setenv()
  fs/fs_test.go
  fs/fs_unix_test.go
  fs/fs_windows_test.go
Labels: testing
